### ISSUE TITLE
코드 에디터에 라인표시 기능을 추가해주세요!!

### ISSUE THREAD

**Issue by riroan** [wonjinYi/lollang-playground#2]
지금 컴파일에러가 났을 때 위에서부터 한줄씩 세면서 에러난 부분을 찾아야 합니다.
라인표시가 있다면 에러난 부분을 쉽게 찾을 수 있을거 같아요!

**Comment by wonjinYi** [comment]
현재는 코드에디터가 단순 textarea로 구성되어있습니다.
빠른시일내에 오픈소스 웹 코드에디터로 대체할 예정입니다. (코드미러 고려중)
그 때 라인표시 기능 추가하겠습니다. 
** 아울러, 현재 구현되지 않은 역탭(Shift Tab)과 코드하이라이팅 기능 추가될 예정입니다.

**Comment by wonjinYi** [comment]
마음이 바뀌었습니다. 코드미러 안쓰고 다른거 주워다가 붙였습니다.
우선 라인표시, 탭/백탭 기능 반영되었습니다.

**Comment by riroan** [comment]
빠른 반영 감사합니다.

![123](https://user-images.githubusercontent.com/33053284/158378343-5b257b50-9591-4276-9a1e-acfecf616e23.png)

근데 라인숫자랑 코드랑 줄이 안맞는거 같습니다.. ㅠㅠ

## 실행 환경
OS : Ubuntu 20.04
Chrome : 99.0.4844.51

**Comment by riroan** [comment]
그리구 리드미에 제 아이디가 잘못 나와있어요
