### ISSUE TITLE
라인표시 개선요청

### ISSUE THREAD

**Issue by riroan** [wonjinYi/lollang-playground#3]
![123](https://user-images.githubusercontent.com/33053284/158530991-8d1bd13b-51e7-4387-b310-de6cea3eea05.png)
코드 라인이 100줄, 1000줄이 넘어가는경우 사진과같이 밑에 스크롤이 생기면서 숫자가 짤려서 보입니다.
라인표시 부분의 width를 6자리정도 숫자까지 포함하도록 늘리거나 자릿수에 맞춰서 변화하면 좋을거 같습니다!

**Comment by wonjinYi** [comment]
저도 고민했던 부분인데, 1000줄 이상의 코드가 나올일이 없다고 생각해서 현재처럼 3자리숫자까지만 라인넘버를 표시하도록 구성했습니다.

라인넘버 자릿수에 따라 라인넘버 표시부 width를 바꾸는건 생각을 못해봤네요. 해당 내용 반영하겠습니다.

**Comment by riroan** [comment]
빠른 수정 감사합니다
