### ISSUE TITLE
파일확장자 변경 .lo -> .lola

### ISSUE THREAD

**Issue by wonjinYi** [wonjinYi/lollang-playground#4]
https://github.com/riroan/lollang/commit/623183514b0673aaec1f49f5ad2089542f3e31a7

**Comment by riroan** [comment]
TIA

**Comment by wonjinYi** [comment]
주문하신 .lola 나왔습니다.
![image](https://user-images.githubusercontent.com/25413566/161245817-b8003eac-96b5-4050-8e12-cf315d52848a.png)

**Comment by riroan** [comment]
와 못본사이에 syntax highlighting까지 되네요
