### ISSUE TITLE
함수 사용시 하이라이팅 누락

### ISSUE THREAD

**Issue by kyn02242** [wonjinYi/lollang-playground#5]
![image](https://user-images.githubusercontent.com/70257475/163802935-e917c9e4-367e-4e37-825b-29c271dec8f5.png)

함수의 선언 부분에서 '나가라 그냥'의 나가라 부분의 하이라이팅이 정상 출력되지 않는것이 확인 되었습니다. 확인 부탁드립니다

**Comment by wonjinYi** [comment]
![image](https://user-images.githubusercontent.com/25413566/163803562-03360fa0-3e9c-4732-b7f2-d2318cef0d7b.png)
현재 내용 반영되었습니다. 이슈 감사합니다.
